import type { Metadata } from "next";
// 1. Import the Lexend font
import { Lexend } from "next/font/google"; 
import "./globals.css";
import { Suspense, lazy } from "react";
import ComponentLoader from "@/components/ComponentLoader";
import NextTopLoader from "nextjs-toploader";

// 2. Define the Lexend font instance
const lexend = Lexend({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lexend", // Define a CSS variable for Tailwind configuration
});

// Lazy load layout components
const Header = lazy(() => import("@/components/layout/Header"));
const Footer = lazy(() => import("@/components/layout/Footer"));

// === Metadata ===
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// === Root Layout ===
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // 3. Apply the font's CSS variable class to the body
        className={`${lexend.variable} antialiased font-lexend`} 
        suppressHydrationWarning
      >
        <NextTopLoader
          color="#6366f1"
          height={3}
          showSpinner={false}
          speed={200}
          shadow="0 0 10px #6366f1,0 0 5px #6366f1"
        />
        <Suspense
          fallback={<ComponentLoader height="h-16" message="Loading header..." />}
        >
          <Header />
        </Suspense>

        <main>{children}</main>

        <Suspense
          fallback={<ComponentLoader height="h-32" message="Loading footer..." />}
        >
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}